site_name: "Standard Operating Procedures of the HCPh project"
site_description: Templates and bootstrapping documentation for MRI standard operating procedures (SOPs)
site_author: The AxonLab

# Copyright
copyright: Copyright © 2023

nav:
    - Home: index.md
    - Change History: changes.md
    - Recruitment, Scheduling, and Screening:
      - Recruitment and screening: recruitment-scheduling-screening/recruitment.md
      - Scheduling: recruitment-scheduling-screening/scheduling.md
    - Data collection:
      - Overall experimental settings: data-collection/intro.md
      - Preliminary work: data-collection/preliminary.md
      - Before each session: data-collection/pre-session.md
      - Preparing the participant: data-collection/participant-prep.md
      - Notes on the scanner's console and recording devices: data-collection/scanning-notes.md
      - Running the scanning session: data-collection/scanning.md
      - Session tear-down: data-collection/tear-down.md
      - Emergency procedures: data-collection/emergency-procedures.md
    - Data management:
      - Before data acquisition (storage preparation): data-management/preliminary.md
      - Post-session retrieval and BIDS: data-management/post-session.md
      - QC of unprocessed data: data-management/mriqc.md
    - Preprocessing: preprocessing.md
    - Release of data: release.md
theme:
  name: material
  palette:
    primary: black
  logo: assets/images/chuv_logo.svg
  features:
    # - tabs
    - navigation.instant
    # - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
  icon:
    admonition:
      thanks: octicons/code-of-conduct-16
      quote: fontawesome/solid/comment-dots
      danger: fontawesome/solid/biohazard
      important: fontawesome/solid/circle-exclamation

plugins:
  - search
  - macros:
      include_dir: include
      include_yaml:
        - secrets: 'secrets/settings.yml'
        - settings: 'study-settings.yml'
      on_undefined: lax
  - mkpdfs:
      company: Lausanne University Hospital (CHUV)
      author: The Axon Lab
      toc_title: Table of Contents
      design: design/report.css
      output_path: pdf/documentation.pdf

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - include/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
