version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/miniforge3
    steps:
      - checkout
      - run:
          name: Create Conda environment
          command: conda create -n myenv python=3.8 -y
      - run:
          name: Install system dependencies
          command: conda install -n myenv -c conda-forge cairo -y
      - run:
          name: Install requirements
          command: |
            source activate myenv
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            source activate myenv
            mkdocs build --site-dir _SOPs_preview
      - store_artifacts:
          path: _SOPs_preview
workflows:
  version: 2
  commit:
    jobs:
      - build

