version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libcairo2 libpango-1.0-0 fonts-dejavu-core
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            mkdocs build --site-dir _site_preview
      - store_artifacts:
          path: _site_preview

workflows:
  version: 2
  commit:
    jobs:
      - build

