version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/miniforge3
    steps:
      - checkout
      - run:
          name: Create Conda environment
          command: |
            conda create -n myenv python=3.8
            conda activate myenv
      - run:
          name: Install system dependencies
          command: |
            conda install -c conda-forge cairo
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            mkdocs build --site-dir _site_preview
      - store_artifacts:
          path: _site_preview

workflows:
  version: 2
  commit:
    jobs:
      - build

