version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/miniforge3
    steps:
      - checkout
      - run:
          name: Initialize conda
          command: |
            echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Create Conda environment
          command: |
            conda create -n myenv python=3.8
            conda activate myenv
      - run:
          name: Install system dependencies
          command: |
            conda install -c conda-forge cairo
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            conda activate myenv
            mkdocs build --site-dir _SOPs_preview
      - store_artifacts:
          path: _SOPs_preview
workflows:
  version: 2
  commit:
    jobs:
      - build

